#!/bin/bash
set -ex

echo "Running tests..."

ROCK_PATH="$1"
export PYTHON_IMAGE="ubuntu/chiselled-python:test"

/snap/rockcraft/current/bin/skopeo copy --insecure-policy \
    oci-archive:"$ROCK_PATH" docker-daemon:"$PYTHON_IMAGE"

CURRENT_DIR="$(dirname "$(readlink -f "$0")")"

for test_dir in "$CURRENT_DIR"/*/
do
    pushd "$test_dir"

    ./runtest

    popd
done
