#!/bin/bash
set -ex

echo "Running tests..."

export PYTHON_IMAGE="ubuntu/chiselled-python:test"

skopeo copy --insecure-policy oci-archive:"$1" docker-daemon:"$PYTHON_IMAGE"

CURRENT_DIR="$(dirname "$(readlink -f "$0")")"

for test_dir in "$CURRENT_DIR"/*/
do
    pushd "$test_dir"

    ./runtest

    popd
done
