ARG UBUNTU_RELEASE=20.04
ARG USER=ubuntu UID=101 GROUP=ubuntu GID=101
ARG CHISEL_VERSION=0.10.0

FROM ubuntu:$UBUNTU_RELEASE AS builder
ARG USER UID GROUP GID TARGETARCH CHISEL_VERSION
SHELL ["/bin/bash", "-oeux", "pipefail", "-c"]
ADD https://github.com/canonical/chisel/releases/download/v${CHISEL_VERSION}/chisel_v${CHISEL_VERSION}_linux_${TARGETARCH}.tar.gz chisel.tar.gz
RUN tar -xvf chisel.tar.gz -C /usr/bin/
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /rootfs/etc \
    && echo "$GROUP:x:$GID:" >/rootfs/etc/group \
    && echo "$USER:x:$UID:$GID::/nohome:/noshell" >/rootfs/etc/passwd
RUN chisel cut --root /rootfs \
    base-files_base \
    base-files_release-info \
    libgcc-s1_libs \
    libc6_libs \
    openssl_config \
    ncurses-base_xterm \
    python3.8_standard

FROM scratch
ARG UID GID
USER $UID:$GID
COPY --from=builder /rootfs /
# The ca-certificates_data slice seems inadequate for the python3.8 image.
# TODO: figure out what is missing and/or how to make the current slice work
#   and remove the next two lines afterwards.
COPY --from=builder /etc/ssl/ /etc/ssl/
COPY --from=builder /usr/share/ca-certificates/mozilla/ /usr/share/ca-certificates/mozilla/

ENTRYPOINT [ "python3.8" ]
