#!/bin/bash
set -ex

echo "Running test for Hello World app..."

test() {
	docker run --rm -v "$PWD/src":/src:ro "$1" \
		exec -IT python3 /src/main.py | \
		grep "Hello World"
}

test "$PYTHON_IMAGE"
