name: Build and Publish Rocks

on:
  push:
    branches: [main, '*.*-*.*']
  pull_request:
    branches: [main, '*.*-*.*']
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ghcr-upload: ${{ steps.read-ci-config.outputs.ghcr-upload }}
      build-matrix: ${{ steps.override-matrix.outputs.build-matrix }}
      upload-matrix: ${{ steps.override-matrix.outputs.upload-matrix }}
      is-release: ${{ steps.branch.outputs.is_release }}
      arch-map: ${{ steps.set-map.outputs.arch-map }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Read .github/ci.yaml
        id: read-ci-config
        uses: canonical/rocks-template-actions/actions/read-ci-config@v1

      - name: Check release branch
        id: branch
        run: |
          if [[ "${GITHUB_REF_NAME}" =~ ^[1-9]\.[0-9]+-[0-9]{2}\.(04|10)$ ]]; then
            echo "is_release=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_release=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set Architecture Map
        id: set-map
        run: |
          if [[ "${{ github.repository_owner }}" != "canonical" ]]; then
            echo 'arch-map={"amd64":["ubuntu-24.04"],"arm64":["ubuntu-24.04-arm"]}' >> $GITHUB_OUTPUT
          fi
      
      # TODO: Template doesn't create the artifact-name correctly when rockcraft.yaml is at the root level
      # This is a temporary workaround to override the artifact-name in the build-matrix and upload-matrix
      - name: Override artifact-name in matrix
        id: override-matrix
        env:
          BUILD_MATRIX: ${{ steps.read-ci-config.outputs.build-matrix }}
          UPLOAD_MATRIX: ${{ steps.read-ci-config.outputs.upload-matrix }}
        run: |
          echo "Overriding artifact-name in build-matrix and upload-matrix"
          build_matrix="$BUILD_MATRIX"
          upload_matrix="$UPLOAD_MATRIX"

          # read name and version from rockcraft.yaml and override artifact-name in build-matrix and upload-matrix
          rockcraft_file=$(find . -name "rockcraft.yaml" | head -n 1)
          name=$(yq eval '.name' "$rockcraft_file")
          tag=$(yq eval '.version' "$rockcraft_file")

          new_build_matrix=$(echo "$build_matrix" | jq -c --arg name "$name" --arg tag "$tag" '(.include[] | select(has("artifact-name"))) |= . + {"artifact-name": ($name + "-" + $tag)}')
          new_upload_matrix=$(echo "$upload_matrix" | jq -c --arg name "$name" --arg tag "$tag" '(.include[] | select(has("artifact-name"))) |= . + {"artifact-name": ($name + "-" + $tag)}')
          echo "build-matrix=$new_build_matrix" >> $GITHUB_OUTPUT
          echo "upload-matrix=$new_upload_matrix" >> $GITHUB_OUTPUT


  build:
    needs: [prepare]
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.build-matrix) }}
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      rock-repo: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
      rock-repo-commit: ${{ github.head_ref || github.ref_name }}
      rockfile-directory: ${{ matrix.directory }}
      oci-archive-name: ${{ matrix.artifact-name }}
      arch-map: ${{ needs.prepare.outputs.arch-map }}
      rockcraft-test: ${{ matrix.run-tests }}
      pro-services: ${{ matrix.pro-services }}
    secrets:
      source-github-token: ${{ secrets.REPO_CLONER_TOKEN }}
      pro-token: ${{ secrets[matrix.pro-token] }}
      pro-artifact-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}


  test:
    needs: [prepare, build]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.build-matrix) }}
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@main
    with:
      oci-archive-name: ${{ matrix.artifact-name }}
    secrets:
      pro-artifact-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}


  upload-ghcr:
    needs: [prepare, test]
    runs-on: ubuntu-latest
    if: |
      needs.prepare.outputs.ghcr-upload == 'true' &&
      needs.prepare.outputs.is-release == 'true' &&
      github.event_name != 'pull_request'
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.build-matrix) }}
      fail-fast: false
    permissions:
      packages: write
    steps:
      - name: Pre-Check Pro Enabled Rocks
        if: ${{ github.event.repository.visibility == 'public' && matrix.pro-services != '' }}
        run: |
          echo "::warning::Uploading Pro enabled rocks to GHCR is not allowed for public repositories."
      
      - name: Upload Rock to GHCR
        if: ${{ github.event.repository.visibility != 'public' || matrix.pro-services == '' }}
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          decrypt-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}


  upload-registries:
    needs: [prepare, test]
    runs-on: ubuntu-latest
    if: |
      fromJSON(needs.prepare.outputs.upload-matrix).include[0] != null &&
      needs.prepare.outputs.is-release == 'true' &&
      github.event_name != 'pull_request'
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.upload-matrix) }}
      fail-fast: false
    steps:
      - name: Prepare ECR Session Token
        if: ${{ contains(matrix.registry-auth-method, 'ecr') }}
        id: get-ecr-token
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[matrix.registry-auth-username] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.registry-auth-password] }}
        run: |
          session_token=$(aws ${{ matrix.registry-auth-method }} \
                          get-login-password \
                          --region ${{ matrix.registry-auth-region }} \
                          )
          echo "::add-mask::$session_token"
          echo "aws-session-token=$session_token" >> $GITHUB_OUTPUT

      - name: Upload Rock to ECR
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        if: ${{ contains(matrix.registry-auth-method, 'ecr') }}
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ${{ matrix.registry-uri }}
          username: AWS
          password: ${{ steps.get-ecr-token.outputs.aws-session-token }}
          decrypt-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}

      - name: Upload Rock to Registry
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        if: matrix.registry-auth-method == 'basic'
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ${{ matrix.registry-uri }}
          username: ${{ secrets[matrix.registry-auth-username] }}
          password: ${{ secrets[matrix.registry-auth-password] }}
          decrypt-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}