name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        version: ["3.8", "3.10", "3.11", "3.12", "3.13"]
        runner: ["X64", "ARM64"]

    steps:
      - uses: actions/checkout@v4

      - name: Build python${{ matrix.version }} rock
        id: build
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: python${{ matrix.version }}/
          verbosity: debug

      - name: Run tests
        run: |
          set -ex
          ./tests/run-all-tests "${{ steps.build.outputs.rock }}"

      - uses: actions/upload-artifact@v4
        with:
          name: python${{ matrix.version }}-${{ matrix.runner }}-rock
          path: ${{ steps.build.outputs.rock }}
