name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.8"]

    steps:
      - uses: actions/checkout@v4

      - name: Build python${{ matrix.version}} rock
        id: build
        uses: canonical/craft-actions/rockcraft-pack@main
        with:
          path: python${{ matrix.version }}/
          verbosity: debug

      - name: Run tests
        env:
          ROCK_PATH: ${{ steps.build.outputs.rock }}
        run: |
          set -ex
          ./tests/run-all-tests "$ROCK_PATH"

      - uses: actions/upload-artifact@v4
        env:
          ROCK_PATH: ${{ steps.build.outputs.rock }}
        with:
          name: rock
          path: "$ROCK_PATH"
